import type { Metadata } from "next";
// import { Inter as FontSans } from "next/font/google";

import { GeistSans } from "geist/font/sans";
import { GeistMono } from "geist/font/mono";

import "./globals.css";

import { cn } from "@/lib/utils";
import { Navigation } from "./Navigation";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={cn(
          "min-h-screen bg-background font-sans antialiased",
          GeistMono.className
        )}
      >
        <Navigation />
        {children}
      </body>
    </html>
  );
}
