import type { Metadata } from "next";

import { Inter as FontSans } from "next/font/google";

import "./globals.css";

import { cn } from "@/lib/utils";
import { Navigation } from "./Navigation";

const fontSans = FontSans({
  subsets: ["latin"],
  variable: "--font-sans",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={cn(
          "min-h-screen bg-background font-sans antialiased",
          fontSans.variable
        )}
      >
        <Navigation />
        <main role="main" className="py-12">
          {children}
        </main>
        <footer role="contentinfo" className="py-12 max-w-site mx-auto px-site">
          <pre className="flex flex-col gap-3 p-4 bg-muted border rounded-md">
            <div className="flex items-center gap-3">
              <span className="text-xs text-foreground/50">
                NEXT_PUBLIC_SUPABASE_URL:
              </span>
              <span className="truncate text-xs font-mono">
                {process.env.NEXT_PUBLIC_SUPABASE_URL}
              </span>
            </div>
            <hr />
            <div className="flex items-center gap-3">
              <span className="text-xs text-foreground/50">
                NEXT_PUBLIC_SUPABASE_ANON_KEY:
              </span>
              <span className="truncate text-xs font-mono">
                {process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY}
              </span>
            </div>
          </pre>
        </footer>
      </body>
    </html>
  );
}
